<?php
/**
 * Deep search for the exact broken URL pattern
 */

global $wpdb;

// The exact broken pattern from the user
$broken_url = '%20%20%20https://mohawkmedibles.ca';

echo "Searching entire database for broken URL pattern...\n\n";

// Search ALL tables
$tables = $wpdb->get_results("SHOW TABLES", ARRAY_N);

$found = array();

foreach ($tables as $table) {
    $table_name = $table[0];

    // Get columns
    $columns = $wpdb->get_results("SHOW COLUMNS FROM `$table_name`", ARRAY_A);

    foreach ($columns as $column) {
        $col_name = $column['Field'];
        $col_type = $column['Type'];

        // Only search text-like columns
        if (strpos($col_type, 'char') !== false ||
            strpos($col_type, 'text') !== false ||
            strpos($col_type, 'blob') !== false) {

            $result = $wpdb->get_var($wpdb->prepare(
                "SELECT COUNT(*) FROM `$table_name` WHERE `$col_name` LIKE %s",
                '%' . $wpdb->esc_like($broken_url) . '%'
            ));

            if ($result > 0) {
                $found[] = array(
                    'table' => $table_name,
                    'column' => $col_name,
                    'count' => $result
                );
                echo "FOUND in $table_name.$col_name ($result rows)\n";
            }
        }
    }
}

if (empty($found)) {
    echo "Pattern '%20%20%20https' NOT found in database.\n";
    echo "\nThis broken URL was likely:\n";
    echo "1. Manually typed/pasted incorrectly\n";
    echo "2. Generated by a browser/tool error\n";
    echo "3. A one-time crawl error\n";
}

// Also check navigation menus
echo "\n\n=== Checking Navigation Menus ===\n";
$menus = wp_get_nav_menus();
foreach ($menus as $menu) {
    $items = wp_get_nav_menu_items($menu->term_id);
    if ($items) {
        foreach ($items as $item) {
            if (strpos($item->url, '%20') !== false || strpos($item->url, '  ') !== false) {
                echo "BROKEN MENU ITEM: {$item->title} => {$item->url}\n";
            }
        }
    }
}
echo "Menu check complete.\n";
