<?php
/**
 * Master SEO Optimization Script
 * Generated: 2026-01-02T01:14:42.593252
 * Total Fixes: 29
 *
 * Run with: wp eval-file master_seo_fix.php
 */

echo "═══════════════════════════════════════════════════════\n";
echo "  MOHAWK MEDIBLES SEO OPTIMIZATION\n";
echo "  Generated by GSC Optimizer Agent\n";
echo "  Fixes: 29\n";
echo "═══════════════════════════════════════════════════════\n\n";

$start_time = microtime(true);
$fixes_applied = 0;


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/edibles/...
// Priority: critical | Reason: Category page with 124,764 impressions but only 1.02% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: edibles
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'edibles';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/flower/...
// Priority: critical | Reason: Category page with 106,643 impressions but only 0.34% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: flower
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'flower';
$new_title = 'Cannabis Flower | Premium Buds | Mohawk Medibles Canada';
$new_meta = 'Shop premium cannabis flower at Mohawk Medibles Canada. AAAA quality buds, indica, sativa & hybrid strains. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/vape/...
// Priority: critical | Reason: Category page with 103,153 impressions but only 1.36% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: vape
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'vape';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/...
// Priority: high | Reason: Position 6.3 with 108,862 impressions but only 2.24% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Shop
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'shop';
$new_meta = 'Order Shop at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/drizzle-fact...
// Priority: high | Reason: Position 5.0 with 49,967 impressions but only 2.86% CTR (expected: 10.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Drizzle Factory  Vape Pen 1 1G
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'drizzle-factory-thc-vape-pen-1-1g';
$new_meta = 'Buy Drizzle Factory  Vape Pen 1 1G online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/accessories/papers-cones/back...
// Priority: high | Reason: Position 9.5 with 43,441 impressions but only 2.05% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Backwoods Cigar
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'backwoods-cigar';
$new_meta = 'Order Backwoods Cigar at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/nicotine/zolt-pouches/...
// Priority: high | Reason: Position 7.8 with 35,475 impressions but only 3.00% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Zolt Pouches
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'zolt-pouches';
$new_meta = 'Order Zolt Pouches at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/nicotine/...
// Priority: high | Reason: Category page with 33,007 impressions but only 0.08% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: nicotine
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'nicotine';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/straight-goo...
// Priority: high | Reason: Position 8.1 with 32,848 impressions but only 3.47% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Straight Goods Dual Chamber Vape 6 Gram
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'straight-goods-dual-chamber-vape-6-gram';
$new_meta = 'Buy Straight Goods Dual Chamber Vape 6 Gram online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian s...';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/concentrates/...
// Priority: high | Reason: Category page with 27,960 impressions but only 0.08% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: concentrates
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'concentrates';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/edibles/candy/gum...
// Priority: high | Reason: Category page with 25,568 impressions but only 0.13% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: gummies
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'gummies';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/edibles/candy/gummies/top-tie...
// Priority: high | Reason: Position 17.5 with 22,575 impressions but only 1.22% CTR (expected: 4.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Top Tier  Gummies 500Mg
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'top-tier-thc-gummies-500mg';
$new_meta = 'Order Top Tier  Gummies 500Mg at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/cactus-labs-glock-9-thc-...
// Priority: high | Reason: Position 7.7 with 21,947 impressions but only 3.37% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Cactus Labs Glock 9  Liquid Diamond Vape Pen
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'cactus-labs-glock-9-thc-liquid-diamond-vape-pen';
$new_meta = 'Buy Cactus Labs Glock 9  Liquid Diamond Vape Pen online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canad...';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/nicotine/geek-max-18ml-nicoti...
// Priority: medium | Reason: Position 3.8 with 16,029 impressions but only 1.26% CTR (expected: 10.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Geek Max 18Ml Nicotine Vape
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'geek-max-18ml-nicotine-vape';
$new_meta = 'Buy Geek Max 18Ml Nicotine Vape online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vapes-2/disposables/drizzle-f...
// Priority: medium | Reason: Position 4.6 with 15,191 impressions but only 2.34% CTR (expected: 10.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Drizzle Factory  Vape Pen 1 1G
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'drizzle-factory-thc-vape-pen-1-1g';
$new_meta = 'Buy Drizzle Factory  Vape Pen 1 1G online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/concentrates/oils/medibles-ho...
// Priority: medium | Reason: Position 11.3 with 14,571 impressions but only 1.85% CTR (expected: 4.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Medibles House Hash Oil
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'medibles-house-hash-oil';
$new_meta = 'Order Medibles House Hash Oil at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/nicotine/pouches/euro-zyn-sli...
// Priority: medium | Reason: Position 8.5 with 14,368 impressions but only 2.42% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Euro Zyn Slim Nicotine Pouches
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'euro-zyn-slim-nicotine-pouches';
$new_meta = 'Order Euro Zyn Slim Nicotine Pouches at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CATEGORY_FIX: https://mohawkmedibles.ca/product-category/concentrates/hash...
// Priority: medium | Reason: Category page with 10,797 impressions but only 0.28% CTR
// ═══════════════════════════════════════════════════════
<?php
/**
 * Fix Category Page SEO: hash
 * Generated by GSC Optimizer Agent
 * Target: Improve CTR from low to 3-5%+
 */

$category_slug = 'hash';
$new_title = 'THC Edibles | Gummies & Chocolates | Mohawk Medibles Canada';
$new_meta = 'Buy THC edibles online at Mohawk Medibles Canada. Gummies, chocolates, beverages & more. Precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Get the term
$term = get_term_by('slug', $category_slug, 'product_cat');
if (!$term) {
    echo "Category not found: $category_slug\n";
    exit;
}

// Update Yoast SEO meta
update_term_meta($term->term_id, '_yoast_wpseo_title', $new_title);
update_term_meta($term->term_id, '_yoast_wpseo_metadesc', $new_meta);

// Update RankMath if installed
if (function_exists('rank_math')) {
    update_term_meta($term->term_id, 'rank_math_title', $new_title);
    update_term_meta($term->term_id, 'rank_math_description', $new_meta);
}

echo "Updated category: $category_slug\n";
echo "  Title: $new_title\n";
echo "  Meta: $new_meta\n";


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/burn-vape-pe...
// Priority: medium | Reason: Position 7.3 with 10,787 impressions but only 2.96% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Burn Vape Pen
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'burn-vape-pen';
$new_meta = 'Buy Burn Vape Pen online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/hemp-geek-di...
// Priority: medium | Reason: Position 6.5 with 10,284 impressions but only 1.90% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Hemp Geek Disposable  Vape
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'hemp-geek-disposable-thc-vape';
$new_meta = 'Buy Hemp Geek Disposable  Vape online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/thc-vapes/thc-disposable/driz...
// Priority: medium | Reason: Position 3.9 with 9,391 impressions but only 2.28% CTR (expected: 10.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Drizzle Factory  Vape Pen 1 1G
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'drizzle-factory-thc-vape-pen-1-1g';
$new_meta = 'Buy Drizzle Factory  Vape Pen 1 1G online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/nicotine/pouches/zolt-8mg-and...
// Priority: medium | Reason: Position 8.6 with 9,209 impressions but only 2.04% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Zolt 8Mg And 15Mg Nicotine Pouches
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'zolt-8mg-and-15mg-nicotine-pouches';
$new_meta = 'Order Zolt 8Mg And 15Mg Nicotine Pouches at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/burn-dual-ch...
// Priority: medium | Reason: Position 7.4 with 8,070 impressions but only 2.07% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Burn Dual Chamber Vape 6 Gram
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'burn-dual-chamber-vape-6-gram';
$new_meta = 'Buy Burn Dual Chamber Vape 6 Gram online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/straight-goo...
// Priority: medium | Reason: Position 9.9 with 7,779 impressions but only 2.65% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Straight Goods 2 Gram
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'straight-goods-2-gram';
$new_meta = 'Buy Straight Goods 2 Gram online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/gas-gang-1g-...
// Priority: medium | Reason: Position 7.7 with 7,309 impressions but only 2.01% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Gas Gang 1G Disposable
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'gas-gang-1g-disposable';
$new_meta = 'Buy Gas Gang 1G Disposable online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/drizzle-fact...
// Priority: medium | Reason: Position 8.8 with 7,067 impressions but only 1.22% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Drizzle Factory  Glo Pod Vape Pen 2G
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'drizzle-factory-thc-glo-pod-vape-pen-2g';
$new_meta = 'Buy Drizzle Factory  Glo Pod Vape Pen 2G online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian ship...';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/disposables/diamond-conc...
// Priority: medium | Reason: Position 12.1 with 6,872 impressions but only 0.33% CTR (expected: 4.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Diamond Concentrates  Vape Pen 1000Mg Disposable
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'diamond-concentrates-thc-vape-pen-1000mg-disposable';
$new_meta = 'Buy Diamond Concentrates  Vape Pen 1000Mg Disposable online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet C...';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/concentrates/topicals/19-path...
// Priority: medium | Reason: Position 13.1 with 5,740 impressions but only 0.42% CTR (expected: 4.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: 19 Paths  Pain Roll On
 * Generated by GSC Optimizer Agent
 */

$product_slug = '19-paths-cbd-pain-roll-on';
$new_meta = 'Order 19 Paths  Pain Roll On at Mohawk Medibles Canada. Delicious cannabis edibles with precise dosing. Lab-tested. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}


// ═══════════════════════════════════════════════════════
// CTR_IMPROVEMENT: https://mohawkmedibles.ca/shop/vape/drizzle-factory-2g-cartr...
// Priority: medium | Reason: Position 7.8 with 5,160 impressions but only 2.19% CTR (expected: 7.0%)
// ═══════════════════════════════════════════════════════
<?php
/**
 * Improve Product CTR: Drizzle Factory 2G Cartridge
 * Generated by GSC Optimizer Agent
 */

$product_slug = 'drizzle-factory-2g-cartridge';
$new_meta = 'Buy Drizzle Factory 2G Cartridge online at Mohawk Medibles Canada. Premium THC vape with smooth hits. Lab-tested potency. Fast discreet Canadian shipping.';

// Find product by slug
$products = get_posts(array(
    'post_type' => 'product',
    'name' => $product_slug,
    'posts_per_page' => 1
));

if (empty($products)) {
    echo "Product not found: $product_slug\n";
    exit;
}

$product = $products[0];

// Update Yoast meta description
$current_meta = get_post_meta($product->ID, '_yoast_wpseo_metadesc', true);
if (strlen($current_meta) < 120) {
    update_post_meta($product->ID, '_yoast_wpseo_metadesc', $new_meta);
    echo "Updated meta for: {$product->post_title}\n";
    echo "  Old: $current_meta\n";
    echo "  New: $new_meta\n";
} else {
    echo "Meta already optimized for: {$product->post_title}\n";
}



$elapsed = round(microtime(true) - $start_time, 2);
echo "\n═══════════════════════════════════════════════════════\n";
echo "  COMPLETE: $fixes_applied fixes applied in {$elapsed}s\n";
echo "═══════════════════════════════════════════════════════\n";
