"use client";

import { useState, useEffect, useMemo, useCallback, type ReactNode } from "react";
import {
    ShoppingCart, Mail, TrendingUp, DollarSign, Clock, Play, RefreshCw,
    AlertTriangle, Settings, BarChart3, Send, Eye, MousePointerClick,
    CheckCircle, XCircle, ToggleLeft, ToggleRight, Save, Percent,
    Timer, Tag, ChevronDown, ChevronUp, FlaskConical,
} from "lucide-react";

// ─── Design Tokens (unified dark theme, lime accents) ────

const cardClass = "bg-[#0f0f18] border border-white/5 rounded-2xl";
const btnPrimary =
    "px-4 py-2 bg-green-500 text-black font-bold text-xs uppercase tracking-wider rounded-xl hover:bg-green-400 transition-colors disabled:opacity-50";
const btnSecondary =
    "px-3 py-1.5 bg-white/5 text-zinc-400 text-xs font-bold uppercase tracking-wider rounded-xl hover:bg-white/10 transition-colors disabled:opacity-50";

type TabView = "overview" | "settings" | "emails";

// ─── Types ───────────────────────────────────────────────

interface RecoverySettings {
    isEnabled: boolean;
    email1Enabled: boolean;
    email1DelayMs: number;
    email1DiscountPercent: number;
    email1Subject: string;
    email2Enabled: boolean;
    email2DelayMs: number;
    email2DiscountPercent: number;
    email2Subject: string;
    email3Enabled: boolean;
    email3DelayMs: number;
    email3DiscountPercent: number;
    email3Subject: string;
    maxEmailsPerCart: number;
    cartExpiryMs: number;
    autoGenerateDiscountCodes: boolean;
    discountCodePrefix: string;
    discountCodeExpiryHours: number;
    freeShippingOnRecovery: boolean;
}

interface RecentCart {
    id: number;
    email: string;
    userName: string | null;
    cartTotal: number;
    emailsSent: number;
    status: string;
    createdAt: string;
    recoveredAt: string | null;
}

interface EmailBreakdown {
    emailNumber: number;
    total: number;
    converted: number;
    avgDiscount: number;
}

interface VariantStats {
    sent: number;
    opened: number;
    clicked: number;
    converted: number;
    openRate: number;
    clickRate: number;
    conversionRate: number;
}

interface CampaignStats {
    totalEmailsSent: number;
    totalOpened: number;
    totalClicked: number;
    totalConverted: number;
    codesGenerated: number;
    openRate: number;
    clickRate: number;
    conversionRate: number;
}

interface CartStats {
    totalAbandoned: number;
    totalActive: number;
    totalRecovered: number;
    totalExpired: number;
    recoveryRate: number;
    totalRevenueLost: number;
    totalRevenueRecovered: number;
    recentCarts: RecentCart[];
    campaignStats: CampaignStats;
    emailBreakdown: EmailBreakdown[];
    abTestStats: { a: VariantStats; b: VariantStats };
}

interface RecoveryEmail {
    id: number;
    abandonedCartId: number;
    emailNumber: number;
    subject: string;
    recipientEmail: string;
    discountCode: string | null;
    discountPercent: number;
    cartTotal: number;
    status: string;
    sentAt: string;
    subjectVariant: string;
    userName: string | null;
}

// ─── Helpers ─────────────────────────────────────────────

async function apiFetch<T>(params?: string): Promise<T> {
    const url = `/api/admin/cart-recovery/${params ? `?${params}` : ""}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`API error ${res.status}`);
    return res.json();
}

async function apiPost<T>(body: Record<string, unknown>): Promise<T> {
    const res = await fetch("/api/admin/cart-recovery/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(`API error ${res.status}`);
    return res.json();
}

function showToast(msg: string, type: "success" | "error" = "success") {
    // Simple toast fallback — replace with sonner if available
    if (typeof window !== "undefined") {
        const el = document.createElement("div");
        el.textContent = msg;
        el.className = `fixed top-4 right-4 z-[9999] px-4 py-3 rounded-xl text-sm font-semibold shadow-lg transition-opacity ${
            type === "success"
                ? "bg-green-500/90 text-black"
                : "bg-red-500/90 text-white"
        }`;
        document.body.appendChild(el);
        setTimeout(() => {
            el.style.opacity = "0";
            setTimeout(() => el.remove(), 300);
        }, 3000);
    }
}

// ─── Main Page ───────────────────────────────────────────

export default function AbandonedCartsPage() {
    const [activeView, setActiveView] = useState<TabView>("overview");
    const [isProcessing, setIsProcessing] = useState(false);

    return (
        <div>
            <div className="flex items-center justify-between mb-8">
                <div>
                    <h1 className="text-3xl font-bold">Cart Recovery</h1>
                    <p className="text-white/60 mt-1">
                        Track, configure, and recover abandoned shopping carts
                    </p>
                </div>
            </div>

            {/* Sub-navigation */}
            <div className="flex gap-2 border-b border-white/5 pb-3 mb-6">
                {([
                    { id: "overview" as const, label: "Overview", icon: BarChart3 },
                    { id: "settings" as const, label: "Campaign Settings", icon: Settings },
                    { id: "emails" as const, label: "Recovery Emails", icon: Mail },
                ] as const).map((tab) => {
                    const Icon = tab.icon;
                    return (
                        <button
                            key={tab.id}
                            onClick={() => setActiveView(tab.id)}
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-colors ${
                                activeView === tab.id
                                    ? "bg-green-500/20 text-green-400 border border-green-500/30"
                                    : "text-zinc-400 hover:text-white hover:bg-white/5 border border-transparent"
                            }`}
                        >
                            <Icon size={14} />
                            {tab.label}
                        </button>
                    );
                })}
            </div>

            {activeView === "overview" && (
                <OverviewPanel isProcessing={isProcessing} setIsProcessing={setIsProcessing} />
            )}
            {activeView === "settings" && <SettingsPanel />}
            {activeView === "emails" && <EmailsPanel />}
        </div>
    );
}

// ─── Overview Panel ─────────────────────────────────────

function OverviewPanel({
    isProcessing,
    setIsProcessing,
}: {
    isProcessing: boolean;
    setIsProcessing: (v: boolean) => void;
}) {
    const [stats, setStats] = useState<CartStats | null>(null);
    const [settings, setSettings] = useState<RecoverySettings | null>(null);
    const [processing, setProcessing] = useState(false);

    const loadData = useCallback(async () => {
        try {
            const [s, se] = await Promise.all([
                apiFetch<CartStats>("action=stats"),
                apiFetch<RecoverySettings>("action=settings"),
            ]);
            setStats(s);
            setSettings(se);
        } catch {
            // silent
        }
    }, []);

    useEffect(() => {
        loadData();
    }, [loadData]);

    const handleProcess = async () => {
        setProcessing(true);
        setIsProcessing(true);
        try {
            const result = await apiPost<{ processed: number; emailsSent: number }>({
                action: "process",
            });
            showToast(`Processed ${result.processed} carts, sent ${result.emailsSent} emails`);
            loadData();
        } catch (err) {
            showToast(String(err), "error");
        } finally {
            setProcessing(false);
            setIsProcessing(false);
        }
    };

    const campaignStats = stats?.campaignStats;
    const emailBreakdown = stats?.emailBreakdown || [];

    return (
        <div className="space-y-6">
            {/* Campaign Status Banner */}
            <div className={`${cardClass} p-4 ${settings?.isEnabled ? "border-green-500/20" : "border-red-500/20"}`}>
                <div className="flex items-center gap-3">
                    {settings?.isEnabled ? (
                        <div className="w-2.5 h-2.5 rounded-full bg-green-500 animate-pulse" />
                    ) : (
                        <div className="w-2.5 h-2.5 rounded-full bg-red-500" />
                    )}
                    <span className="text-sm font-bold">
                        Cart Recovery Campaign: {settings?.isEnabled ? "Active" : "Paused"}
                    </span>
                    {settings?.isEnabled && (
                        <span className="text-xs text-zinc-500 ml-auto">
                            Auto-generating {settings.autoGenerateDiscountCodes ? "unique" : "static"} discount codes
                        </span>
                    )}
                </div>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                {[
                    { label: "Abandoned Carts", value: stats?.totalAbandoned || 0, icon: ShoppingCart, color: "text-amber-400" },
                    { label: "Active Carts", value: stats?.totalActive || 0, icon: Clock, color: "text-blue-400" },
                    { label: "Recovered", value: stats?.totalRecovered || 0, icon: TrendingUp, color: "text-green-400" },
                    { label: "Revenue Recovered", value: `$${Number(stats?.totalRevenueRecovered || 0).toFixed(2)}`, icon: DollarSign, color: "text-green-400" },
                ].map((stat, i) => {
                    const Icon = stat.icon;
                    return (
                        <div key={i} className={`${cardClass} p-4`}>
                            <div className="flex items-center gap-2 mb-1">
                                <Icon size={14} className={stat.color} />
                                <span className="text-zinc-500 text-xs uppercase tracking-wider">{stat.label}</span>
                            </div>
                            <p className="text-xl font-black">{typeof stat.value === "string" ? stat.value : stat.value.toLocaleString()}</p>
                        </div>
                    );
                })}
            </div>

            {/* Recovery Performance */}
            <div className={`${cardClass} p-6`}>
                <h3 className="text-sm font-bold uppercase tracking-wider mb-4">Recovery Performance</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div>
                        <p className="text-zinc-500 text-xs uppercase tracking-wider mb-1">Recovery Rate</p>
                        <p className="text-3xl font-black text-green-400">{stats?.recoveryRate || 0}%</p>
                        <div className="w-full bg-white/5 rounded-full h-2 mt-2">
                            <div
                                className="bg-green-500 h-2 rounded-full transition-all"
                                style={{ width: `${Math.min(stats?.recoveryRate || 0, 100)}%` }}
                            />
                        </div>
                    </div>
                    <div>
                        <p className="text-zinc-500 text-xs uppercase tracking-wider mb-1">Expired Carts</p>
                        <p className="text-3xl font-black">{stats?.totalExpired || 0}</p>
                        <p className="text-zinc-500 text-xs mt-1">carts that expired without recovery</p>
                    </div>
                    <div>
                        <p className="text-zinc-500 text-xs uppercase tracking-wider mb-1">Revenue at Risk</p>
                        <p className="text-3xl font-black text-red-400">${Number(stats?.totalRevenueLost || 0).toFixed(2)}</p>
                        <p className="text-zinc-500 text-xs mt-1">from active + expired carts</p>
                    </div>
                </div>
            </div>

            {/* Campaign Email Stats */}
            {campaignStats && campaignStats.totalEmailsSent > 0 && (
                <div className={`${cardClass} p-6`}>
                    <h3 className="text-sm font-bold uppercase tracking-wider mb-4">Email Campaign Performance</h3>
                    <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-6">
                        {[
                            { label: "Emails Sent", value: campaignStats.totalEmailsSent, icon: Send, color: "text-blue-400" },
                            { label: "Open Rate", value: `${campaignStats.openRate}%`, icon: Eye, color: "text-purple-400" },
                            { label: "Click Rate", value: `${campaignStats.clickRate}%`, icon: MousePointerClick, color: "text-amber-400" },
                            { label: "Conversion Rate", value: `${campaignStats.conversionRate}%`, icon: CheckCircle, color: "text-green-400" },
                            { label: "Codes Generated", value: campaignStats.codesGenerated, icon: Tag, color: "text-green-400" },
                        ].map((stat, i) => {
                            const Icon = stat.icon;
                            return (
                                <div key={i} className="bg-white/5 rounded-xl p-3 text-center">
                                    <Icon size={16} className={`${stat.color} mx-auto mb-1`} />
                                    <p className="text-lg font-black">{stat.value}</p>
                                    <p className="text-zinc-500 text-[10px] uppercase tracking-wider">{stat.label}</p>
                                </div>
                            );
                        })}
                    </div>

                    {/* Per-email breakdown */}
                    {emailBreakdown.length > 0 && (
                        <div>
                            <h4 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-3">Per-Email Breakdown</h4>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                                {emailBreakdown.map((eb) => {
                                    const convRate = eb.total > 0 ? ((eb.converted / eb.total) * 100).toFixed(1) : "0.0";
                                    const colors = ["border-l-blue-400", "border-l-amber-400", "border-l-red-400"];
                                    return (
                                        <div key={eb.emailNumber} className={`bg-white/5 rounded-xl p-3 border-l-4 ${colors[eb.emailNumber - 1] || "border-l-zinc-400"}`}>
                                            <p className="font-bold text-sm mb-1">Email {eb.emailNumber}</p>
                                            <div className="flex justify-between text-xs">
                                                <span className="text-zinc-500">Sent: <span className="font-bold text-white">{eb.total}</span></span>
                                                <span className="text-zinc-500">Converted: <span className="text-green-400 font-bold">{eb.converted}</span></span>
                                                <span className="text-zinc-500">Rate: <span className="text-green-400 font-bold">{convRate}%</span></span>
                                            </div>
                                            {eb.avgDiscount > 0 && (
                                                <p className="text-zinc-500 text-[10px] mt-1">Avg discount: {eb.avgDiscount.toFixed(0)}%</p>
                                            )}
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* 3-Email Sequence Visual */}
            <div className={`${cardClass} p-6`}>
                <h3 className="text-sm font-bold uppercase tracking-wider mb-4">Active Recovery Sequence</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {[
                        {
                            email: "Email 1",
                            delay: settings ? `${settings.email1DelayMs / 60000} min` : "60 min",
                            discount: settings?.email1DiscountPercent || 0,
                            enabled: settings?.email1Enabled ?? true,
                            subject: settings?.email1Subject || "Gentle Reminder",
                            color: "border-l-blue-400",
                            dotColor: "bg-blue-400",
                        },
                        {
                            email: "Email 2",
                            delay: settings ? `${Math.round(settings.email2DelayMs / 3600000)} hr` : "24 hr",
                            discount: settings?.email2DiscountPercent || 10,
                            enabled: settings?.email2Enabled ?? true,
                            subject: settings?.email2Subject || "Still Thinking?",
                            color: "border-l-amber-400",
                            dotColor: "bg-amber-400",
                        },
                        {
                            email: "Email 3",
                            delay: settings ? `${Math.round(settings.email3DelayMs / 3600000)} hr` : "72 hr",
                            discount: settings?.email3DiscountPercent || 15,
                            enabled: settings?.email3Enabled ?? true,
                            subject: settings?.email3Subject || "Last Chance",
                            color: "border-l-red-400",
                            dotColor: "bg-red-400",
                        },
                    ].map((seq, i) => (
                        <div key={i} className={`bg-white/5 rounded-xl p-4 border-l-4 ${seq.color} ${!seq.enabled ? "opacity-50" : ""}`}>
                            <div className="flex items-center justify-between mb-2">
                                <div className="flex items-center gap-2">
                                    <div className={`w-2 h-2 rounded-full ${seq.dotColor}`} />
                                    <span className="font-bold text-sm">{seq.email}</span>
                                </div>
                                {!seq.enabled && <span className="text-[10px] text-red-400 font-bold uppercase">Disabled</span>}
                            </div>
                            <div className="flex items-center gap-2 mb-2">
                                <Clock size={12} className="text-zinc-500" />
                                <span className="text-xs text-zinc-500">After {seq.delay}</span>
                            </div>
                            <p className="text-zinc-500 text-xs mb-1 truncate" title={seq.subject}>{seq.subject}</p>
                            {seq.discount > 0 ? (
                                <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-green-500/10 text-green-400 text-[10px] font-bold rounded">
                                    <Percent size={10} /> {seq.discount}% OFF
                                </span>
                            ) : (
                                <span className="text-zinc-500 text-[10px]">No discount</span>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {/* A/B Test Performance */}
            {stats?.abTestStats && (stats.abTestStats.a.sent > 0 || stats.abTestStats.b.sent > 0) && (
                <div className={`${cardClass} p-6`}>
                    <h3 className="text-sm font-bold uppercase tracking-wider mb-4 flex items-center gap-2">
                        <FlaskConical size={14} className="text-green-400" /> A/B Test Results
                    </h3>
                    <div className="grid grid-cols-2 gap-4">
                        {(["a", "b"] as const).map((v) => {
                            const d = stats.abTestStats[v];
                            const isWinner =
                                v === "a"
                                    ? stats.abTestStats.a.conversionRate > stats.abTestStats.b.conversionRate
                                    : stats.abTestStats.b.conversionRate > stats.abTestStats.a.conversionRate;
                            return (
                                <div
                                    key={v}
                                    className={`rounded-xl p-4 border-2 ${
                                        isWinner && d.sent > 0
                                            ? "border-green-400/40 bg-green-500/5"
                                            : "border-white/5 bg-white/[0.02]"
                                    }`}
                                >
                                    <div className="flex items-center justify-between mb-3">
                                        <span className="font-bold text-sm">Variant {v.toUpperCase()}</span>
                                        {isWinner && d.sent > 0 && (
                                            <span className="text-[10px] font-bold text-green-400 bg-green-500/10 px-2 py-0.5 rounded uppercase">Winner</span>
                                        )}
                                    </div>
                                    <div className="space-y-2 text-xs">
                                        <div className="flex justify-between"><span className="text-zinc-500">Sent</span><span className="font-bold">{d.sent}</span></div>
                                        <div className="flex justify-between"><span className="text-zinc-500">Open Rate</span><span className="font-bold">{d.openRate}%</span></div>
                                        <div className="flex justify-between"><span className="text-zinc-500">Click Rate</span><span className="font-bold">{d.clickRate}%</span></div>
                                        <div className="flex justify-between"><span className="text-zinc-500">Conversions</span><span className="font-bold text-green-400">{d.converted} ({d.conversionRate}%)</span></div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            )}

            {/* Process Button */}
            <div className={`${cardClass} p-6`}>
                <div className="flex items-center justify-between">
                    <div>
                        <h3 className="text-sm font-bold uppercase tracking-wider mb-1">Process Abandoned Carts</h3>
                        <p className="text-zinc-500 text-xs">
                            Manually trigger the abandoned cart email processor. Checks all pending carts and sends appropriate emails based on timing and settings.
                        </p>
                    </div>
                    <button
                        className={btnPrimary}
                        disabled={processing || isProcessing}
                        onClick={handleProcess}
                    >
                        <span className="flex items-center gap-1.5">
                            {processing ? <RefreshCw size={14} className="animate-spin" /> : <Play size={14} />}
                            {processing ? "Processing..." : "Process Now"}
                        </span>
                    </button>
                </div>
            </div>

            {/* Recent Abandoned Carts */}
            {stats?.recentCarts && stats.recentCarts.length > 0 && (
                <div className={`${cardClass} p-6`}>
                    <h3 className="text-sm font-bold uppercase tracking-wider mb-4">Recent Abandoned Carts</h3>
                    <div className="overflow-x-auto">
                        <table className="w-full text-xs">
                            <thead>
                                <tr className="border-b border-white/5">
                                    <th className="text-left py-2 text-zinc-500 uppercase tracking-wider font-bold">Customer</th>
                                    <th className="text-left py-2 text-zinc-500 uppercase tracking-wider font-bold">Cart Total</th>
                                    <th className="text-left py-2 text-zinc-500 uppercase tracking-wider font-bold">Emails Sent</th>
                                    <th className="text-left py-2 text-zinc-500 uppercase tracking-wider font-bold">Status</th>
                                    <th className="text-left py-2 text-zinc-500 uppercase tracking-wider font-bold">Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {stats.recentCarts.slice(0, 10).map((cart) => (
                                    <tr key={cart.id} className="border-b border-white/5 hover:bg-white/[0.02]">
                                        <td className="py-2">
                                            <p className="font-bold">{cart.userName || "Unknown"}</p>
                                            <p className="text-zinc-500">{cart.email}</p>
                                        </td>
                                        <td className="py-2 text-green-400 font-bold">${Number(cart.cartTotal).toFixed(2)}</td>
                                        <td className="py-2">
                                            <div className="flex gap-1">
                                                {[1, 2, 3].map((n) => (
                                                    <div
                                                        key={n}
                                                        className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                                                            n <= cart.emailsSent
                                                                ? "bg-green-500 text-black"
                                                                : "bg-white/5 text-zinc-500"
                                                        }`}
                                                    >
                                                        {n}
                                                    </div>
                                                ))}
                                            </div>
                                        </td>
                                        <td className="py-2">
                                            <span
                                                className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                                                    cart.status === "recovered"
                                                        ? "bg-green-500/10 text-green-400"
                                                        : cart.status === "active"
                                                          ? "bg-blue-500/10 text-blue-400"
                                                          : cart.status === "expired"
                                                            ? "bg-white/5 text-zinc-500"
                                                            : "bg-red-500/10 text-red-400"
                                                }`}
                                            >
                                                {cart.status}
                                            </span>
                                        </td>
                                        <td className="py-2 text-zinc-500">{new Date(cart.createdAt).toLocaleDateString()}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
}

// ─── Settings Panel ─────────────────────────────────────

function SettingsPanel() {
    const [settings, setSettings] = useState<RecoverySettings | null>(null);
    const [form, setForm] = useState<Record<string, unknown>>({});
    const [expanded, setExpanded] = useState<string | null>("general");
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        apiFetch<RecoverySettings>("action=settings").then(setSettings).catch(() => {});
    }, []);

    const merged = useMemo(
        () => ({
            isEnabled: (form.isEnabled ?? settings?.isEnabled ?? true) as boolean,
            email1Enabled: (form.email1Enabled ?? settings?.email1Enabled ?? true) as boolean,
            email1DelayMinutes: (form.email1DelayMinutes ?? (settings ? settings.email1DelayMs / 60000 : 60)) as number,
            email1DiscountPercent: (form.email1DiscountPercent ?? settings?.email1DiscountPercent ?? 0) as number,
            email1Subject: (form.email1Subject ?? settings?.email1Subject ?? "") as string,
            email2Enabled: (form.email2Enabled ?? settings?.email2Enabled ?? true) as boolean,
            email2DelayMinutes: (form.email2DelayMinutes ?? (settings ? settings.email2DelayMs / 60000 : 1440)) as number,
            email2DiscountPercent: (form.email2DiscountPercent ?? settings?.email2DiscountPercent ?? 10) as number,
            email2Subject: (form.email2Subject ?? settings?.email2Subject ?? "") as string,
            email3Enabled: (form.email3Enabled ?? settings?.email3Enabled ?? true) as boolean,
            email3DelayMinutes: (form.email3DelayMinutes ?? (settings ? settings.email3DelayMs / 60000 : 4320)) as number,
            email3DiscountPercent: (form.email3DiscountPercent ?? settings?.email3DiscountPercent ?? 15) as number,
            email3Subject: (form.email3Subject ?? settings?.email3Subject ?? "") as string,
            maxEmailsPerCart: (form.maxEmailsPerCart ?? settings?.maxEmailsPerCart ?? 3) as number,
            cartExpiryDays: (form.cartExpiryDays ?? (settings ? settings.cartExpiryMs / 86400000 : 7)) as number,
            autoGenerateDiscountCodes: (form.autoGenerateDiscountCodes ?? settings?.autoGenerateDiscountCodes ?? true) as boolean,
            discountCodePrefix: (form.discountCodePrefix ?? settings?.discountCodePrefix ?? "RECOVER") as string,
            discountCodeExpiryHours: (form.discountCodeExpiryHours ?? settings?.discountCodeExpiryHours ?? 48) as number,
            freeShippingOnRecovery: (form.freeShippingOnRecovery ?? settings?.freeShippingOnRecovery ?? false) as boolean,
        }),
        [settings, form],
    );

    const hasChanges = Object.keys(form).length > 0;

    const handleSave = async () => {
        setSaving(true);
        try {
            const updates: Record<string, unknown> = {};
            for (const [key, val] of Object.entries(form)) {
                if (key === "cartExpiryDays") {
                    updates.cartExpiryDays = Number(val);
                } else {
                    updates[key] = val;
                }
            }
            await apiPost({ action: "updateSettings", settings: updates });
            showToast("Campaign settings updated!");
            setForm({});
            // Reload settings
            const fresh = await apiFetch<RecoverySettings>("action=settings");
            setSettings(fresh);
        } catch (err) {
            showToast(String(err), "error");
        } finally {
            setSaving(false);
        }
    };

    const set = (key: string, val: unknown) => setForm((prev) => ({ ...prev, [key]: val }));

    const Section = ({ id, title, icon: Icon, children }: { id: string; title: string; icon: typeof Settings; children: ReactNode }) => (
        <div className={`${cardClass} overflow-hidden`}>
            <button
                className="w-full flex items-center justify-between p-4 hover:bg-white/[0.02] transition-colors"
                onClick={() => setExpanded(expanded === id ? null : id)}
            >
                <div className="flex items-center gap-2">
                    <Icon size={14} className="text-green-400" />
                    <span className="text-sm font-bold uppercase tracking-wider">{title}</span>
                </div>
                {expanded === id ? <ChevronUp size={14} className="text-zinc-500" /> : <ChevronDown size={14} className="text-zinc-500" />}
            </button>
            {expanded === id && <div className="px-4 pb-4 space-y-4 border-t border-white/5">{children}</div>}
        </div>
    );

    const Toggle = ({ label, value, onChange, description }: { label: string; value: boolean; onChange: (v: boolean) => void; description?: string }) => (
        <div className="flex items-center justify-between py-2">
            <div>
                <p className="text-sm font-bold">{label}</p>
                {description && <p className="text-zinc-500 text-xs mt-0.5">{description}</p>}
            </div>
            <button onClick={() => onChange(!value)} className="text-green-400">
                {value ? <ToggleRight size={28} /> : <ToggleLeft size={28} className="text-zinc-500" />}
            </button>
        </div>
    );

    const NumberInput = ({
        label,
        value,
        onChange,
        min,
        max,
        suffix,
        description,
    }: {
        label: string;
        value: number;
        onChange: (v: number) => void;
        min: number;
        max: number;
        suffix?: string;
        description?: string;
    }) => (
        <div className="py-2">
            <div className="flex items-center justify-between mb-1">
                <div>
                    <p className="text-sm font-bold">{label}</p>
                    {description && <p className="text-zinc-500 text-xs mt-0.5">{description}</p>}
                </div>
                <div className="flex items-center gap-2">
                    <input
                        type="number"
                        min={min}
                        max={max}
                        value={value}
                        onChange={(e) => onChange(Number(e.target.value))}
                        className="w-20 bg-white/5 border border-white/10 rounded-lg px-2 py-1 text-white text-sm text-right focus:outline-none focus:border-green-500/50"
                    />
                    {suffix && <span className="text-zinc-500 text-xs">{suffix}</span>}
                </div>
            </div>
        </div>
    );

    const TextInput = ({ label, value, onChange, description }: { label: string; value: string; onChange: (v: string) => void; description?: string }) => (
        <div className="py-2">
            <p className="text-sm font-bold mb-1">{label}</p>
            {description && <p className="text-zinc-500 text-xs mb-2">{description}</p>}
            <input
                type="text"
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-green-500/50"
            />
        </div>
    );

    return (
        <div className="space-y-4">
            {/* Save Bar */}
            {hasChanges && (
                <div className="sticky top-0 z-10 bg-[#0a0a0f]/95 backdrop-blur border border-green-500/30 rounded-xl p-3 flex items-center justify-between">
                    <span className="text-green-400 text-xs font-bold uppercase tracking-wider">Unsaved changes</span>
                    <div className="flex gap-2">
                        <button className={btnSecondary} onClick={() => setForm({})}>
                            Discard
                        </button>
                        <button className={btnPrimary} onClick={handleSave} disabled={saving}>
                            <span className="flex items-center gap-1.5">
                                <Save size={12} />
                                {saving ? "Saving..." : "Save Changes"}
                            </span>
                        </button>
                    </div>
                </div>
            )}

            {/* General Settings */}
            <Section id="general" title="General Settings" icon={Settings}>
                <Toggle
                    label="Enable Cart Recovery Campaign"
                    value={merged.isEnabled}
                    onChange={(v) => set("isEnabled", v)}
                    description="When disabled, no recovery emails will be sent"
                />
                <NumberInput
                    label="Max Emails Per Cart"
                    value={merged.maxEmailsPerCart}
                    onChange={(v) => set("maxEmailsPerCart", v)}
                    min={1}
                    max={3}
                    suffix="emails"
                    description="Maximum number of recovery emails to send per abandoned cart"
                />
                <NumberInput
                    label="Cart Expiry"
                    value={merged.cartExpiryDays}
                    onChange={(v) => set("cartExpiryDays", v)}
                    min={1}
                    max={30}
                    suffix="days"
                    description="Days before an abandoned cart expires and is no longer eligible for recovery"
                />
            </Section>

            {/* Email 1 Settings */}
            <Section id="email1" title="Email 1 -- Gentle Reminder" icon={Mail}>
                <Toggle label="Enable Email 1" value={merged.email1Enabled} onChange={(v) => set("email1Enabled", v)} />
                <NumberInput
                    label="Delay After Abandonment"
                    value={merged.email1DelayMinutes}
                    onChange={(v) => set("email1DelayMinutes", v)}
                    min={1}
                    max={10080}
                    suffix="minutes"
                    description={`Currently: ${merged.email1DelayMinutes >= 60 ? `${(merged.email1DelayMinutes / 60).toFixed(1)} hours` : `${merged.email1DelayMinutes} minutes`}`}
                />
                <NumberInput
                    label="Discount Percentage"
                    value={merged.email1DiscountPercent}
                    onChange={(v) => set("email1DiscountPercent", v)}
                    min={0}
                    max={100}
                    suffix="%"
                    description="Set to 0 for no discount on first email"
                />
                <TextInput label="Email Subject" value={merged.email1Subject} onChange={(v) => set("email1Subject", v)} />
            </Section>

            {/* Email 2 Settings */}
            <Section id="email2" title="Email 2 -- Urgency + Discount" icon={Timer}>
                <Toggle label="Enable Email 2" value={merged.email2Enabled} onChange={(v) => set("email2Enabled", v)} />
                <NumberInput
                    label="Delay After Abandonment"
                    value={merged.email2DelayMinutes}
                    onChange={(v) => set("email2DelayMinutes", v)}
                    min={1}
                    max={10080}
                    suffix="minutes"
                    description={`Currently: ${merged.email2DelayMinutes >= 60 ? `${(merged.email2DelayMinutes / 60).toFixed(1)} hours` : `${merged.email2DelayMinutes} minutes`}`}
                />
                <NumberInput
                    label="Discount Percentage"
                    value={merged.email2DiscountPercent}
                    onChange={(v) => set("email2DiscountPercent", v)}
                    min={0}
                    max={100}
                    suffix="%"
                />
                <TextInput label="Email Subject" value={merged.email2Subject} onChange={(v) => set("email2Subject", v)} />
            </Section>

            {/* Email 3 Settings */}
            <Section id="email3" title="Email 3 -- Last Chance" icon={AlertTriangle}>
                <Toggle label="Enable Email 3" value={merged.email3Enabled} onChange={(v) => set("email3Enabled", v)} />
                <NumberInput
                    label="Delay After Abandonment"
                    value={merged.email3DelayMinutes}
                    onChange={(v) => set("email3DelayMinutes", v)}
                    min={1}
                    max={10080}
                    suffix="minutes"
                    description={`Currently: ${merged.email3DelayMinutes >= 60 ? `${(merged.email3DelayMinutes / 60).toFixed(1)} hours` : `${merged.email3DelayMinutes} minutes`}`}
                />
                <NumberInput
                    label="Discount Percentage"
                    value={merged.email3DiscountPercent}
                    onChange={(v) => set("email3DiscountPercent", v)}
                    min={0}
                    max={100}
                    suffix="%"
                />
                <TextInput label="Email Subject" value={merged.email3Subject} onChange={(v) => set("email3Subject", v)} />
            </Section>

            {/* Discount Code Settings */}
            <Section id="discounts" title="Discount Code Settings" icon={Tag}>
                <Toggle
                    label="Auto-Generate Unique Codes"
                    value={merged.autoGenerateDiscountCodes}
                    onChange={(v) => set("autoGenerateDiscountCodes", v)}
                    description="Generate unique one-time-use discount codes for each cart. When off, uses static codes (COMEBACK10, LASTCHANCE15)"
                />
                <TextInput
                    label="Code Prefix"
                    value={merged.discountCodePrefix}
                    onChange={(v) => set("discountCodePrefix", v)}
                    description="Prefix for auto-generated codes (e.g., RECOVER-A3B7K2)"
                />
                <NumberInput
                    label="Code Expiry"
                    value={merged.discountCodeExpiryHours}
                    onChange={(v) => set("discountCodeExpiryHours", v)}
                    min={1}
                    max={720}
                    suffix="hours"
                    description="How long auto-generated discount codes remain valid"
                />
                <Toggle
                    label="Free Shipping on Recovery"
                    value={merged.freeShippingOnRecovery}
                    onChange={(v) => set("freeShippingOnRecovery", v)}
                    description="Include free shipping with recovery discount codes"
                />
            </Section>
        </div>
    );
}

// ─── Emails Panel ───────────────────────────────────────

function EmailsPanel() {
    const [emails, setEmails] = useState<RecoveryEmail[] | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        apiFetch<RecoveryEmail[]>("action=emails&limit=50")
            .then(setEmails)
            .catch(() => setEmails([]))
            .finally(() => setLoading(false));
    }, []);

    if (loading) {
        return (
            <div className="flex items-center justify-center py-12">
                <RefreshCw size={20} className="animate-spin text-zinc-500" />
            </div>
        );
    }

    if (!emails || emails.length === 0) {
        return (
            <div className={`${cardClass} p-8 text-center`}>
                <Mail size={32} className="text-zinc-500 mx-auto mb-3" />
                <p className="font-bold mb-1">No Recovery Emails Sent Yet</p>
                <p className="text-zinc-500 text-xs">
                    Recovery emails will appear here once the cart abandonment processor runs and sends emails to customers.
                </p>
            </div>
        );
    }

    const statusColors: Record<string, string> = {
        sent: "bg-blue-500/10 text-blue-400",
        delivered: "bg-green-500/10 text-green-400",
        opened: "bg-purple-500/10 text-purple-400",
        clicked: "bg-amber-500/10 text-amber-400",
        converted: "bg-green-500/10 text-green-400",
        failed: "bg-red-500/10 text-red-400",
    };

    return (
        <div className={`${cardClass} overflow-hidden`}>
            <div className="p-4 border-b border-white/5">
                <h3 className="text-sm font-bold uppercase tracking-wider">Recovery Email Log</h3>
                <p className="text-zinc-500 text-xs mt-1">All cart recovery emails sent to customers</p>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-xs">
                    <thead>
                        <tr className="border-b border-white/5 bg-white/[0.02]">
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">#</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Recipient</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Subject</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Email</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Discount</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Cart</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Variant</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Status</th>
                            <th className="text-left px-4 py-2 text-zinc-500 uppercase tracking-wider font-bold">Sent</th>
                        </tr>
                    </thead>
                    <tbody>
                        {emails.map((email) => (
                            <tr key={email.id} className="border-b border-white/5 hover:bg-white/[0.02]">
                                <td className="px-4 py-2">
                                    <div
                                        className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold ${
                                            email.emailNumber === 1
                                                ? "bg-blue-500/20 text-blue-400"
                                                : email.emailNumber === 2
                                                  ? "bg-amber-500/20 text-amber-400"
                                                  : "bg-red-500/20 text-red-400"
                                        }`}
                                    >
                                        {email.emailNumber}
                                    </div>
                                </td>
                                <td className="px-4 py-2">
                                    <p className="font-bold">{email.userName || "Unknown"}</p>
                                    <p className="text-zinc-500">{email.recipientEmail}</p>
                                </td>
                                <td className="px-4 py-2 text-zinc-400 max-w-[200px] truncate" title={email.subject}>
                                    {email.subject}
                                </td>
                                <td className="px-4 py-2 text-zinc-500">Email {email.emailNumber}</td>
                                <td className="px-4 py-2">
                                    {email.discountCode ? (
                                        <div>
                                            <span className="text-green-400 font-mono font-bold">{email.discountCode}</span>
                                            <p className="text-zinc-500 text-[10px]">{email.discountPercent}% off</p>
                                        </div>
                                    ) : (
                                        <span className="text-zinc-600">---</span>
                                    )}
                                </td>
                                <td className="px-4 py-2 text-green-400 font-bold">${Number(email.cartTotal).toFixed(2)}</td>
                                <td className="px-4 py-2">
                                    {email.subjectVariant === "b" ? (
                                        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-green-500/10 text-green-400">B</span>
                                    ) : (
                                        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-white/5 text-zinc-500">A</span>
                                    )}
                                </td>
                                <td className="px-4 py-2">
                                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${statusColors[email.status] || "bg-white/5 text-zinc-500"}`}>
                                        {email.status}
                                    </span>
                                </td>
                                <td className="px-4 py-2 text-zinc-500">{new Date(email.sentAt).toLocaleString()}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
